### PR TITLE
9

### LINKED ISSUE #40: Update to Drupal 9.3.5
Currently the Drupal version shipped is  8.9.20, which is way behind the stable release and is no longer supported.

For security and stability i recommend updating to Drupal 9.

### PR DESCRIPTION
**Pull request by yalh76**
## Problem

- *Fix #40*

## Solution

- *Upgrade to 9.3.5~ynh1*

## PR Status

- [ ] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by yalh76** [comment]
!testme

**Comment by yalh76** [comment]
!testme

**Comment by yalh76** [comment]
!testme

**Comment by JamesClarke7283** [comment]
### I ran:
`sudo yunohost app upgrade drupal__2 -u https://github.com/YunoHost-Apps/drupal_ynh/tree/9 --debug`

And the upgrade from 8.9.20 to 9.3.5 failed.

### Here is the log:
https://paste.yunohost.org/raw/exuxojapen

**Comment by yalh76** [comment]
> ### I ran:
> 
> `sudo yunohost app upgrade drupal__2 -u https://github.com/YunoHost-Apps/drupal_ynh/tree/9 --debug`
> 
> And the upgrade from 8.9.20 to 9.3.5 failed.
> ### Here is the log:
> 
> https://paste.yunohost.org/raw/exuxojapen

I hope it was on a testing Yunohost / drupal because this PR is far from ready ...

**Comment by JamesClarke7283** [comment]
> > ### I ran:
> > `sudo yunohost app upgrade drupal__2 -u https://github.com/YunoHost-Apps/drupal_ynh/tree/9 --debug`
> > And the upgrade from 8.9.20 to 9.3.5 failed.
> > ### Here is the log:
> > https://paste.yunohost.org/raw/exuxojapen
> 
> I hope it was on a testing Yunohost / drupal because this PR is far from ready ...

It was on testing, dont worry.

**Comment by yalh76** [comment]
!testme

**Comment by JamesClarke7283** [comment]
Ran it again, it worked!!

**Comment by yalh76** [comment]
great, I will wait for complete package_check before merging

**Comment by yalh76** [comment]
Own CI result for Revision: 9b9b01a3882d4f2d6fc84b0cdd2055d515d00b24 

image

**Pull request merged**
